### ISSUE TITLE
[Component] Side navigation (enhancement)

### ISSUE THREAD

**Issue by danielmutis** [canonical/vanilla-framework#4452]
### Component design
- [ ] UX
- [ ] Visual
- [ ] UX spec
- [ ] UX spec signed off

### Accessibility
- [ ] Accessibility spec ([template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit))
- [ ] Accessibility signed off 

### Figma file
- [ ] Vanilla figma file "future" label ([library](https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library))
- [ ] Vanilla figma file "current" label 

### Development
- [ ] Development spec ([template](https://docs.google.com/document/d/17yFEYUSnZBGofhVt6f-w-P2WytSxFOsm8LLYA7fDlbg/edit#heading=h.tgxqhvxolnmv))
- [ ] Development

### Release
- [ ] Vanilla release 
- [ ] Discourse published on design system category ([link](https://discourse.ubuntu.com/c/design-system/98))

**Comment by bartaz** [comment]
Closing as a relic of the past.
